export const GET_NAVIGATION_OPEN = 'GET_NAVIGATION_OPEN';
export const GET_NAVIGATION_INDEX = 'GET_NAVIGATION_INDEX';
export const GET_WINDOW_DIMENSIONS = 'GET_WINDOW_DIMENSIONS';
export const GET_BREADCRUMBS = 'GET_BREADCRUMBS';
export const GET_TABS = 'GET_TABS';

export const GET_USER = 'GET_USER';
