export const SET_NAVIGATION_OPEN = 'SET_NAVIGATION_OPEN';
export const SET_NAVIGATION_INDEX = 'SET_NAVIGATION_INDEX';
export const SET_WINDOW_DIMENSIONS = 'SET_WINDOW_DIMENSIONS';
export const SET_BREADCRUMBS = 'SET_BREADCRUMBS';
export const SET_TABS = 'SET_TABS';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_STOP = 'LOGIN_STOP';
export const SET_USER_DATA = 'SET_USER_DATA';
export const CLEAR_USER_DATA = 'CLEAR_USER_DATA';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
